#pragma once

#include "donut/types.hpp"

// key ideas:
// 1. monitor is XY-plane, Z-axis comes out of screen, origin at center of screen.
// 2. the object is always located in the square [-100, 100] x [-100, 100]
// 3. 'canvas' is the screen (XY-plane) divided into pixels, depending on the resolution.

// TODO: select brightness depending on terminal resolution
// TODO: change points generated by shapes.cpp depending on terminal resolution
// TODO: customizable rotate speed
// TODO: edit each necessary pixel instead of re-printing everything?
// TODO: cache the data points instead of calculating on the fly
// TODO: light blocked by other parts of the object ?!

namespace donut::core {

std::string move_cursor(int row, int col);
void update_screen(grd& canvas, grd& old_canvas);
std::pair<int, int> get_terminal_size();
void rotate_shape(ves& points, ves& normals, vec degrees);
void draw(grd& canvas, ves& points, ves& normals);

}
